# Generated by Django 3.2.13 on 2022-05-19 09:41

from django.db import migrations, models
import follow.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
            managers=[
                ('manager', follow.managers.FollowManager()),
            ],
        ),
    ]
