# Generated by Django 3.2.13 on 2022-05-03 16:18

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220503_2110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bunch',
            managers=[
                ('manager', users.managers.BunchManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='follow',
            managers=[
                ('manager', users.managers.FollowManager()),
            ],
        ),
    ]
