# Generated by Django 3.2.13 on 2022-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220503_2118'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bunch',
            name='unique_bunch',
        ),
        migrations.AddConstraint(
            model_name='bunch',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='unique_bunch'),
        ),
    ]
