# Generated by Django 3.2.13 on 2022-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='uploads/users/user_default.png', upload_to='uploads/users/', verbose_name='Фото'),
        ),
    ]
