# Generated by Django 3.2.13 on 2022-05-07 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rating.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('0', '-'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default=0, max_length=1, verbose_name='Оценка')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_from', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
            managers=[
                ('manager', rating.managers.RatingManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user_to', 'user_from'), name='unique_rating'),
        ),
    ]
