# Generated by Django 3.2.13 on 2022-05-21 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hometasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_hometask', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hometask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometask', to='hometasks.hometask', verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hometask', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('student', 'hometask'), name='unique_assignment'),
        ),
    ]
