# Generated by Django 3.2.13 on 2022-05-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0003_auto_20220504_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinemodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='users.user'),
            preserve_default=False,
        ),
    ]
