# Generated by Django 3.2.13 on 2022-05-19 09:41

import bunch.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Finished', 'Finished')], default='Waiting', help_text='Поставьте стстус', max_length=16, verbose_name='Статус')),
                ('datetime', models.CharField(default=None, max_length=10, verbose_name='Время занятия')),
            ],
            options={
                'verbose_name': 'Связка',
                'verbose_name_plural': 'Связки',
                'ordering': ('datetime',),
            },
            managers=[
                ('manager', bunch.managers.BunchManager()),
            ],
        ),
    ]
