# Generated by Django 3.2.13 on 2022-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('подписки', 'подписки'), ('рейтинг', 'рейтинг'), ('уроки', 'уроки')], max_length=20, verbose_name='категория')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='дата получения')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
    ]
