# Generated by Django 3.2.13 on 2022-05-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата получения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='initiator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
