# Generated by Django 3.2.13 on 2022-05-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_alter_notificationmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='category',
            field=models.CharField(choices=[('подписки', 'подписки'), ('рейтинг', 'рейтинг'), ('уроки', 'уроки')], max_length=20, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='initiator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_notifications', to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель'),
        ),
    ]
