# Generated by Django 3.2.13 on 2022-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220515_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='category',
            field=models.CharField(choices=[('подписки', 'подписки'), ('рейтинг', 'рейтинг')], max_length=20, verbose_name='категория'),
        ),
    ]
