# Generated by Django 3.2.13 on 2022-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220518_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
