# Generated by Django 3.2.13 on 2022-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='category',
            field=models.CharField(choices=[('подписки', 'подписки'), ('рейтинг', 'рейтинг'), ('уроки', 'уроки')], max_length=20, verbose_name='категория'),
        ),
    ]
